import ApolloWrapper from '@/components/ApolloWrapper'; // Importe ton wrapper
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: 'Headless Wordpress Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>

        <ApolloWrapper>
          <header className='w-full mx-auto flex justify-center items-center py-5'>
            <nav className="px-3 flex gap-5">
              <Link href={"/"}>Accueil</Link>
              <Link href={"/blog"}>Blog</Link>
            </nav>
          </header>
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}